project_id = "wzjjabjkgxlgvqgteppd"

[functions.analyze-text]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.cleanup-old-reports]
verify_jwt = false

[functions.sync-storage-db]
verify_jwt = false

[functions.admin-auth]
verify_jwt = false

[functions.admin-cleanup]
verify_jwt = false