// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzjjabjkgxlgvqgteppd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6amphYmprZ3hsZ3ZxZ3RlcHBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MjU4MjYsImV4cCI6MjA2NzAwMTgyNn0.7f5qS-ZzvP77XT1EzQvNj_IDs3CPtTR7jwYAjrBN05o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});